title: Analyzing Inflation and Economic Trends: A Comparative Data Analysis of U.S. and German CPI, GDP, and Inflation Across Presidential and Chancellor Tenures
description: This is the final project of our Data Science class exploring economic trends of US and Germany.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
